---
title: Multi-omics integration analysis
output:
  html_document:
    toc: true
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(plotly)
library(knitr)
library(kableExtra)
library(DT)
library(formattable)
library(dplyr)
library(rtracklayer)
library(ggplot2)
library(rmarkdown)
```


```{r echo = FALSE, warning = FALSE, message = FALSE}
source("/home/DeepEA/galaxy/tools/4-MULTI-OMICS_ANALYSIS/multi-omics-integration/functions.R")
cmrMat <- read.table(cmrDir, sep = "\t", header = T, quote = "", stringsAsFactors = F)
cmrMat <- na.omit(cmrMat)
colnames(cmrMat) <- c("geneID", "cmrLevel", "omics1", "omics2")
cmrGene <- cmrMat$geneID
# transform to relative abundance
if(method == "ecdf"){
  cmrMat$cmrLevel <- ecdf(cmrMat$cmrLevel)(cmrMat$cmrLevel)
  cmrMat$omics1 <- ecdf(cmrMat$omics1)(cmrMat$omics1)
  cmrMat$omics2 <- ecdf(cmrMat$omics2)(cmrMat$omics2)
}else if(method == "z-score"){
  cmrMat$cmrLevel <- (cmrMat$cmrLevel - mean(cmrMat$cmrLevel, na.rm = T))/sd(cmrMat$cmrLevel, na.rm = T)
  cmrMat$omics1 <- (cmrMat$omics1 - mean(cmrMat$omics1, na.rm = T))/sd(cmrMat$omics1, na.rm = T)
  cmrMat$omics2 <- (cmrMat$omics2 - mean(cmrMat$omics2, na.rm = T))/sd(cmrMat$omics2, na.rm = T)
}else{
  cmrMat$cmrLevel <- (cmrMat$cmrLevel - min(cmrMat$cmrLevel))/(max(cmrMat$cmrLevel) - min(cmrMat$cmrLevel))
  cmrMat$omics1 <- (cmrMat$omics1 - min(cmrMat$omics1))/(max(cmrMat$omics1) - min(cmrMat$omics1))
  cmrMat$omics2 <- (cmrMat$omics2 - min(cmrMat$omics2))/(max(cmrMat$omics2) - min(cmrMat$omics2))
}
```


### Ternary plot
```{r echo = FALSE, warning = FALSE, message = FALSE}
tt <- as.matrix(cmrMat[,2:4])
res <- apply(tt, 1, defineMod)
cmrMat$mod <- res
p <- plot_ly(
  cmrMat, 
  a = ~cmrLevel, 
  b = ~omics1, 
  c = ~omics2, 
  color = ~mod, 
  type = "scatterternary",
  text = ~geneID
) %>% 
layout(
  ternary = list(
    aaxis = axis("CMR"), 
    baxis = axis("Omics1"), 
    caxis = axis("Omics2")
  )
)
p
```

### Detailed tabular
```{r echo = FALSE, warning = FALSE, message = FALSE}
table_options <- function() {
  list(dom = 'Bfrtip',
    pageLength = 8,
    buttons = list(c('copy', 'csv', 'excel', 'pdf')),
    searchHighlight = TRUE,
    colReorder = TRUE,
    scrollX = TRUE,
    fixedColumns = TRUE,
    extensions = 'Responsive',
    deferRender = TRUE,
    scroller = TRUE,
    lengthChange = FALSE
    )
}
colnames(cmrMat) <- c("geneID", "CMR", "Omics 1", "Omics 2", "Category")
datatable(
  cmrMat,
  rownames = FALSE,
  editable = TRUE,
  elementId = "linktable",
  class = 'cell-border',
  escape = FALSE,
  options = table_options(),
  extensions = c('Buttons', 'Select')) %>% 
  formatStyle(columns = colnames(cmrMat), fontSize = '80%')
```

### Functional gene sets enrichment analysis
```{r echo = FALSE, warning = FALSE, message = FALSE}
statMat <- cmrMat %>% group_by(Category) %>% summarize(Count = n())
fileNames <- strsplit(geneList, ",")[[1]]
geneList <- lapply(fileNames, read.table, sep = "\t", header = T, quote = "", stringsAsFactors = F)
bgGene <- read.table(file = bgGeneDir, sep = "\t", header = F, quote = "", stringsAsFactors = F)
bgGene <- bgGene$V1
geneNumber <- length(bgGene)
resMat <- NULL
for(i in 1:nrow(statMat)){
  curType <- statMat$Category[i]
  curGene <- cmrMat %>% filter(Category == curType) %>% pull(geneID)
  curNumber <- statMat$Count[i]
  interGene <- lapply(geneList, function(x) intersect(x[,1], curGene))
  if(enrichMethod == "fisher"){
    interLength <- unlist(lapply(interGene, length))
    resVec <- NULL
    for (j in 1:length(interLength)) {
      p <- fisher.test(matrix(c(length(bgGene), nrow(geneList[[j]]), 
                                       curNumber, interLength[j]), nrow = 2, ncol = 2, byrow = T))$p.value
      resVec <- c(resVec, interLength[j], round(p,3))
    }
    resMat <- rbind(resMat, resVec)
  }
}
colNames <- unlist(lapply(geneList, function(x) colnames(x)))
colnames(resMat) <- c(colNames, paste0(colNames, ".pvalue"))[c(seq(1, length(colNames)*2, 2),
                                                               seq(2, length(colNames)*2, 2))]
statMat <- cbind(statMat, resMat)
func <- function(df, colName){
  res <- df %>% mutate(a = cell_spec(df[,colName], "html",
                                           color = "white",
                                           background = ifelse(df[,colName] < 0.05, "#D7261E", "#1f77b4"),
                                           bold = TRUE))
  res[,colName] <- res[,"a"]
  res <- res %>% select(-a)
  res
}

for(i in colNames){
  statMat <- func(statMat, paste0(i, ".pvalue"))
}

statMat %>% knitr::kable(format = "html", escape = FALSE) %>%  
kableExtra::kable_styling(bootstrap_options = "striped",full_width = FALSE, 
								stripe_color = 'black', latex_options = "bordered")
```


